# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "00 8 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- name: Configure git for a user
    # You may pin to the exact commit or the version.
      #uses: painmanagementcollaboratory/Rolling-Peak-COVID-Data-by-State@v2
      #with:
        # GitHub token
        #token:  ${{github.token}}
        # GitHub username
        #username: ${{github.actor}}
    #- name: Set Name
      #uses: actions/ #painmanagementcollaboratory/Rolling-Peak-COVID-Data-by-State@V2

        
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
        #name: 'PMC'
        #email: 'painmanagementcollaboratory@users.noreply.github.com'
        #actor: 'painmanagementcollaboratory'
        token: '${{ secrets.GH_Token }}'

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pandas numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run Code
      run: |
        python process-data.py
